### ISSUE TITLE
in-game radio freq different from ts3

### ISSUE THREAD

**Issue by KRDucky** [jarangmandi/BFSGSimCom#63]
![IMG_20220302_090215](https://user-images.githubusercontent.com/1669611/156387578-d409e335-c5f5-4f23-aa0f-90dbc6e37363.jpg)

Prepar3D v5.3

**Comment by KRDucky** [comment]
Because the feqs don't match up, it won't move to the correct channel. I am using the latest version of FSUIPC. It's a licensed version.

**Comment by KRDucky** [comment]
It would be nice if it could use simconnect I think. Maybe the issue has to do with FSUIPC?

**Comment by jarangmandi** [comment]
The program uses FSUIPC because it was designed to be 'simulator agnostic' - I fly X-Plane and use XPUIPC which provides a very similar interface. Other members of the BFSG use P3D, MSFS and even FSX!  Simconnect is MS specific.

This is a bit of a weird one as it's clearly a military aircraft - 243.000 is the military guard frequency, right? Troubleshooting is going to be a challenge because I don't have access to P3D of any flavour.

However...

There are two places in the UIPC interface where frequency can come from. One assumes commercial sims where the first digit always represents 100Mhz and is omitted from the returned value and injected by the program; the more recent addition contains a value which returns the whole frequency. There's logic in the program that's supposed to work out which simulator its talking to and select appropriately - that doesn't appear to be working properly in this instance. Fortunately, I put an option to override the logic in the last release (v0.14)

On the "Options", at the bottom, you can force the use of the full frequency value by selecting "Force 8.33kHz" in place of "Let BFSGSimCom decide".

If this doesn't work, then it IS an FSUIPC issue, and I'll need to start thinking about something else. Please give this a try though, and let me know how you get on.

**Comment by KRDucky** [comment]
ah. Ill try the Force 8.33kHz option and yes, its a Milviz aircraft. Also, Simconnect does work in P3D because P3D is literally a licensed clone of Flightsim X. your Simcom X client proves it. Theres the FSX/P3D/MS2020 option and the FSUIPC option. It works with both. But the Simcom X program is very unstable so we are trying to use the TS3 route.

**Comment by KRDucky** [comment]
I was chatting with one of the military guys I know and he was telling me that the 200 and up range is UHF and the less than 200 range is VHF. Could it be that the plugin doesn't support UHF?

**Comment by KRDucky** [comment]
Does the channel name need an @ symbol? 
![Uploading IMG_20220304_103700.jpg…]()
 Because I've renamed the channels to all be under 200 and even when manually changing to the channel freq, it doesn't move

**Comment by jarangmandi** [comment]
> ah. Ill try the Force 8.33kHz option and yes, its a Milviz aircraft. Also, Simconnect does work in P3D because P3D is literally a licensed clone of Flightsim X. your Simcom X client proves it. Theres the FSX/P3D/MS2020 option and the FSUIPC option. It works with both. But the Simcom X program is very unstable so we are trying to use the TS3 route.

Sorry Ian, but Simcom X isn't mine!

**Comment by jarangmandi** [comment]
> ah. Ill try the Force 8.33kHz option and yes, its a Milviz aircraft. Also, Simconnect does work in P3D because P3D is literally a licensed clone of Flightsim X. your Simcom X client proves it.

Sorry - I was unclear - I know P3D is an FSX derivative (although a long way from it now), and therefore supports SimConnect. FSUIPC actually uses SimConnect to talk with these simulators.

>Theres the FSX/P3D/MS2020 option and the FSUIPC option. It works with both. But the Simcom X program is very unstable so we are trying to use the TS3 route.

So - to be clear - Simcom X correctly picks the military UHF frequencies? And this is the case regardless of whether you've selected the SimConnect or the FSUIPC interface option?

**Comment by jarangmandi** [comment]
> I was chatting with one of the military guys I know and he was telling me that the 200 and up range is UHF and the less than 200 range is VHF. Could it be that the plugin doesn't support UHF?

As far as I'm aware, neither SimConnect nor FSUIPC have any concept of UHF or VHF - all they know about is COM radios and the frequencies they're tuned to. It's how the program, whether it be BFSGSimCom or SimcomX, derives those frequencies that's important.

**Comment by jarangmandi** [comment]
> The 8.33kHz option doesn't appear to do anything. It still shows the wrong freq. I haven't found anything in the fsuipc settings to let me fix it

Last questions for now...

You've said it shows the wrong frequency, but not said if it shows a different frequency to the one it showed with the automatic option. Can you provide a list which shows what frequency you have tuned, and what the BFSGSimCom status window shows for each of the available options please?

Also, in TeamSpeak, can you try changing frequency a few times and then go to "Tools/Client Log", make sure all 5 of the check boxes at the top of that dialog are checked, and copy and paste the contents of the text window please?

I have neither P3D 5.3 nor any Milviz aircraft so I'm shooting in the dark a bit.

**Comment by KRDucky** [comment]
If the tuned freq is 239.245, tS3 shows 139.25.
It seems to like to take 3 digit numbers and make them 2 digit as well.

Simcom X does pick up all the freqs without issue and works like a charm except for it being a slow interface and prone to crashing.

**Comment by KRDucky** [comment]
I have a list of 30 freqs that a programmed into the simulator and most of them don't work

**Comment by jarangmandi** [comment]
I think I've spotted a bug. I need you to try the following please...

Can you start TS, open the BFSGSimCom options dialog, select "Force 833" at the bottom and then exit TS immediately. Then start it again and let me know if it works?

If it does, then it's a one line change - perhaps more if I can guess what P3D5.x looks like to FSUIPC (at the moment, I can automatically detect MSFS and X-Plane which both support 833 mode, but want to get it spotting P3D too).

**Comment by jarangmandi** [comment]
OK - one step at a time! It's difficult to read, but it looks like it's picking up the right frequencies from the simulator now so my suspicions about that bug look correct. However, now we're up against something else.

You've obviously worked out that it helps to put the frequency associated with a station in the name of the room. BFSGSimCom looks for a valid frequency in the commercial bands (around 118 to 136 MHz) in the room name though and, as you can see from the data above, any room with a frequency that's outside of these bands doesn't have a "TSFreq" entry against it. It's the TSFreq that it uses to work out which room to move to, so it *should* move you to, say, NQI CLEARANCE if you tune 128.400. If it doesn't, then move yourself to the channel next to it in the list in TS and try. Any chance you can show me a photo of the channel list from your TS window though?

I'm a little confused though as I understood that the military air bands were between 225 and 399 MHz, yet most if not all of the frequencies that you've got there are outside of that range. It looks like that's something you've done to see if you can overcome the fact that BFSGSimCom was only giving you a leading "1", is that right?!

Regardless, it looks like I'm going to need to update BFSGSimCom to consider the military band - although I may well make it optional and selectable from the configuration dialog as it's not mainstream. I don't know when that'll be though...

Thanks for your patience and help pinning this down - we will get there...

**Comment by KRDucky** [comment]
You are correct. I changed the freqs to all be in the 100 series.

I moved the user to the adjacent freq and then tuned 149.00. it automatically moved me back to the lobby. It did not move me to the 149.00 channel.

![IMG_20220310_104435](https://user-images.githubusercontent.com/1669611/157712702-7641d9d2-00b1-4bec-9e43-47c101538413.jpg)
![IMG_20220310_104440](https://user-images.githubusercontent.com/1669611/157712730-0d2ba13e-9fa2-4c9c-8ea1-091d08fd80d3.jpg)

**Comment by KRDucky** [comment]
The radios in the sim go as low as 30.000 and as high as 399.975

**Comment by KRDucky** [comment]
The sim goes in XXX.yyy frequency tuning.
We are currently having issues with our milviz model that it's shortening freqs from the 3 digit yyy to a 2 digit yy. So don't worry on your end about that side. We'll adjust accordingly. We just need the plugin to detect the correct com freq and move the pilot to the correct channel.

**Comment by jarangmandi** [comment]
> I moved the user to the adjacent freq and then tuned 149.00. it automatically moved me back to the lobby. It did not move me to the 149.00 channel.

That's the behaviour I would expect given where we are currently (it's not where we'll be when we've fixed this). BFSGSimCom doesn't recognise 149.00 as a valid frequency and therefore moves you to the lobby when you change frequency because that's where you've said you want to go if you tune an invalid frequency. If you tune 128.400 or 120.900 or 122.425 (which are all valid commercial aviation COM frequencies) you should move to the room with that frequency.

**Comment by jarangmandi** [comment]
> The radios in the sim go as low as 30.000 and as high as 399.975

OK - I've seen similar behaviour in the DCS aircraft I have so I'll make the "Military" option to be between 30.000 and 399.975, and leave the "Commercial" behaviour as it is. I'll be tracking this under a different issue number as it's an enhancement rather than a bug, but will let you know when its done. Would you be happy to test any new version before release?

**Comment by KRDucky** [comment]
Sure. I'll test those "valid freqs" and let you know how it acts

**Comment by KRDucky** [comment]
I have confirmed that it moves channels accordingly

**Comment by jarangmandi** [comment]
I've created a release [here](https://github.com/jarangmandi/BFSGSimCom/releases) which should address the issues we've found. Can you try it for me please? It should install over the top of the version you have.

In the configuration dialog (which has been reorganised because it was getting too long), there's now an option bottom right to all BFSGSimCom to recognise military frequencies in room names (do bear in mind that it's looking for frequencies to be specified with at least 2 decimal places). Please also let me know if the frequencies are correctly picked up when the "Let BFSGSimCom decide" option is selected in the "8.33kHz Channel Spacing" group - although if it doesn't, it should now start working when you force 8.33kHz without needing a TS restart.

Thanks again for your help, and I hope this works for you. Once you've confirmed it does, I'll promote it to a release version.

**Comment by jarangmandi** [comment]
Ian, can you confirm whether the updated version of BFSGSimCom works for you please?

**Comment by KRDucky** [comment]
Just saw this. I'll test it

**Comment by KRDucky** [comment]
It seems to be working. I have encountered a weird issue where on one sim, it connects and works but on another it connects but doesnt change the freqs when I change them in the sim.

**Comment by KRDucky** [comment]
It is changing to the correct freqs as listed in the channel names. I just have to figure out why one of the sim's plugin isnt changing freqs.

**Comment by KRDucky** [comment]
sorted it out. Had to uninstall the old version, then delete all folders and files related to it. Now it works
